# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=100)),
                ('existence', models.CharField(max_length=30)),
            ],
        ),
    ]
